// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vtraffic_light.cpp"
#include "Vtraffic_light___024root__DepSet_h3da28485__0.cpp"
#include "Vtraffic_light___024root__DepSet_hc311587c__0.cpp"
#include "Vtraffic_light__ConstPool_0.cpp"
#include "Vtraffic_light___024root__Slow.cpp"
#include "Vtraffic_light___024root__DepSet_hc311587c__0__Slow.cpp"
#include "Vtraffic_light__Syms.cpp"
